package com.mycompany.project.pojo;
// Generated 1 Sep, 2020 11:19:55 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ContractorLookup generated by hbm2java
 */
@Entity
@Table(name="contractor_lookup"
    ,catalog="project"
)
public class ContractorLookup  implements java.io.Serializable {


     private Integer contractorLookupId;
     private String contractorName;
     private String isActive;

    public ContractorLookup() {
    }

	
    public ContractorLookup(String contractorName) {
        this.contractorName = contractorName;
    }
    public ContractorLookup(String contractorName, String isActive) {
       this.contractorName = contractorName;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="contractor_lookup_id", unique=true, nullable=false)
    public Integer getContractorLookupId() {
        return this.contractorLookupId;
    }
    
    public void setContractorLookupId(Integer contractorLookupId) {
        this.contractorLookupId = contractorLookupId;
    }

    
    @Column(name="contractor_name", nullable=false, length=100)
    public String getContractorName() {
        return this.contractorName;
    }
    
    public void setContractorName(String contractorName) {
        this.contractorName = contractorName;
    }

    
    @Column(name="is_active", length=10)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }




}


