package com.mycompany.project.pojo;
// Generated 1 Sep, 2020 11:19:55 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LabourRoleLookup generated by hbm2java
 */
@Entity
@Table(name="labour_role_lookup"
    ,catalog="project"
)
public class LabourRoleLookup  implements java.io.Serializable {


     private int labourRoleLookupId;
     private String labourRoleName;
     private Integer labourWageTypeLookupId;

    public LabourRoleLookup() {
    }

	
    public LabourRoleLookup(int labourRoleLookupId) {
        this.labourRoleLookupId = labourRoleLookupId;
    }
    public LabourRoleLookup(int labourRoleLookupId, String labourRoleName, Integer labourWageTypeLookupId) {
       this.labourRoleLookupId = labourRoleLookupId;
       this.labourRoleName = labourRoleName;
       this.labourWageTypeLookupId = labourWageTypeLookupId;
    }
   
     @Id 

    
    @Column(name="labour_role_lookup_id", unique=true, nullable=false)
    public int getLabourRoleLookupId() {
        return this.labourRoleLookupId;
    }
    
    public void setLabourRoleLookupId(int labourRoleLookupId) {
        this.labourRoleLookupId = labourRoleLookupId;
    }

    
    @Column(name="labour_role_name", length=100)
    public String getLabourRoleName() {
        return this.labourRoleName;
    }
    
    public void setLabourRoleName(String labourRoleName) {
        this.labourRoleName = labourRoleName;
    }

    
    @Column(name="labour_wage_type_lookup_id")
    public Integer getLabourWageTypeLookupId() {
        return this.labourWageTypeLookupId;
    }
    
    public void setLabourWageTypeLookupId(Integer labourWageTypeLookupId) {
        this.labourWageTypeLookupId = labourWageTypeLookupId;
    }




}


