package com.mycompany.project.pojo;
// Generated 18 Jul, 2020 11:16:34 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LabourWageTypeLookup generated by hbm2java
 */
@Entity
@Table(name="labour_wage_type_lookup"
    ,catalog="project"
)
public class LabourWageTypeLookup  implements java.io.Serializable {


     private int labourWageTypeLookupId;
     private String labourWageTypeName;

    public LabourWageTypeLookup() {
    }

    public LabourWageTypeLookup(int labourWageTypeLookupId, String labourWageTypeName) {
       this.labourWageTypeLookupId = labourWageTypeLookupId;
       this.labourWageTypeName = labourWageTypeName;
    }
   
     @Id 

    
    @Column(name="labour_wage_type_lookup_id", unique=true, nullable=false)
    public int getLabourWageTypeLookupId() {
        return this.labourWageTypeLookupId;
    }
    
    public void setLabourWageTypeLookupId(int labourWageTypeLookupId) {
        this.labourWageTypeLookupId = labourWageTypeLookupId;
    }

    
    @Column(name="labour_wage_type_name", nullable=false, length=100)
    public String getLabourWageTypeName() {
        return this.labourWageTypeName;
    }
    
    public void setLabourWageTypeName(String labourWageTypeName) {
        this.labourWageTypeName = labourWageTypeName;
    }




}


