package com.mycompany.project.pojo;
// Generated 18 Jul, 2020 11:16:34 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LabourChargeLookup generated by hbm2java
 */
@Entity
@Table(name="labour_charge_lookup"
    ,catalog="project"
)
public class LabourChargeLookup  implements java.io.Serializable {


     private int labourChargeLookupId;
     private String labourChargeName;
     private int labourChargeAmount;
     private String isActive;

    public LabourChargeLookup() {
    }

    public LabourChargeLookup(int labourChargeLookupId, String labourChargeName, int labourChargeAmount, String isActive) {
       this.labourChargeLookupId = labourChargeLookupId;
       this.labourChargeName = labourChargeName;
       this.labourChargeAmount = labourChargeAmount;
       this.isActive = isActive;
    }
   
     @Id 

    
    @Column(name="labour_charge_lookup_id", unique=true, nullable=false)
    public int getLabourChargeLookupId() {
        return this.labourChargeLookupId;
    }
    
    public void setLabourChargeLookupId(int labourChargeLookupId) {
        this.labourChargeLookupId = labourChargeLookupId;
    }

    
    @Column(name="labour_charge_name", nullable=false, length=45)
    public String getLabourChargeName() {
        return this.labourChargeName;
    }
    
    public void setLabourChargeName(String labourChargeName) {
        this.labourChargeName = labourChargeName;
    }

    
    @Column(name="labour_charge_amount", nullable=false)
    public int getLabourChargeAmount() {
        return this.labourChargeAmount;
    }
    
    public void setLabourChargeAmount(int labourChargeAmount) {
        this.labourChargeAmount = labourChargeAmount;
    }

    
    @Column(name="is_active", nullable=false, length=45)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }




}


