package com.mycompany.project.pojo;
// Generated 18 Jul, 2020 11:16:34 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Registration generated by hbm2java
 */
@Entity
@Table(name="registration"
    ,catalog="project"
)
public class Registration  implements java.io.Serializable {


     private int regId;
     private String name;
     private BigDecimal khoraki;
     private String isActive;
     private Date createdDatetime;

    public Registration() {
    }

    public Registration(int regId, String name, BigDecimal khoraki, String isActive, Date createdDatetime) {
       this.regId = regId;
       this.name = name;
       this.khoraki = khoraki;
       this.isActive = isActive;
       this.createdDatetime = createdDatetime;
    }
   
     @Id 

    
    @Column(name="reg_id", unique=true, nullable=false)
    public int getRegId() {
        return this.regId;
    }
    
    public void setRegId(int regId) {
        this.regId = regId;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="khoraki", nullable=false, precision=10)
    public BigDecimal getKhoraki() {
        return this.khoraki;
    }
    
    public void setKhoraki(BigDecimal khoraki) {
        this.khoraki = khoraki;
    }

    
    @Column(name="is_active", nullable=false, length=10)
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_datetime", nullable=false, length=19)
    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }
    
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }




}


